version: "3.7" 
services:
  nginx:
    image: nginx:1.21.0
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ".:/var/www/html/"
      - "./nginx.conf:/etc/nginx/nginx.conf"
    links:
      - php
      - mysql
  php:
    build:
      context: .
    image: phpdocker
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ".:/var/www/html/"
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # - ./mysql-dump:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql/
    restart: always
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: simplesvet
      MYSQL_USER: 'simplesvet'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '12345678'
volumes:
 # mysql-dump:
  mysql:
